### ISSUE TITLE
Exercise 1 - Android Build Fail

### ISSUE THREAD

**Issue by DeveloQueer** [MicrosoftDocs/mslearn-xamarin-forms-ui-with-xaml#4]
## Build Error returned even before writing Code

Following the tutorial, right after cloning one is supposed to "verify that the app builds and runs in [their] environment". When building the solution it is succesfull, but when building the Android project (which also runs on the emulator), 1 error and 4 warnings are outputted.

I'm a junior developer so I don't know how to contribute other than stating the errors and creating awareness. Hope it can be fixed and more developers can profit from the great learning tutorials :).

**Error 1/1**
``` error
Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to generate Java type for class: Android.Support.V4.View.Accessibility.AccessibilityManagerCompat/IAccessibilityStateChangeListenerImplementor due to MAX_PATH: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\User\Desktop\mslearn-xamarin-forms-ui-with-xaml\src\exercise1\start\Phoneword\Phoneword.Android\obj\Debug\81\android\src\mono\android\support\v4\view\accessibility\AccessibilityManagerCompat_AccessibilityStateChangeListenerImplementor.java'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Microsoft.Android.Build.Tasks.Files.CopyIfStreamChanged(Stream stream, String destination) in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 170
   at Xamarin.Android.Tasks.GenerateJavaStubs.CreateJavaSources(IEnumerable`1 javaTypes, TypeDefinitionCache cache)	Phoneword.Android		
```	
**Warning 1/4**
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		'Xamarin.Essentials.pdb' is using a deprecated debug information level.
Set the debugging information to Portable in the Visual Studio project property pages or edit the project file in a text editor and set the 'DebugType' MSBuild property to 'portable' to use the newer, cross-platform debug information level.
If this file comes from a NuGet package, update to a newer version of the NuGet package or notify the library author.	Phoneword.Android			
```
**Warning 2/4**
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Assembly 'Xamarin.Android.Support.Annotations' is using a deprecated attribute '[assembly: Java.Interop.DoNotPackageAttribute]'. Use a newer version of this NuGet package or notify the library author.	Phoneword.Android			
```
**Warning 3/4**
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Google Play requires that new applications and updates must use a TargetFrameworkVersion of v10.0 (API level 29) or above. You are currently targeting v8.1 (API level 27).	Phoneword.Android			
```
**Warning 4/4**
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		'Phoneword.pdb' is using a deprecated debug information level.
Set the debugging information to Portable in the Visual Studio project property pages or edit the project file in a text editor and set the 'DebugType' MSBuild property to 'portable' to use the newer, cross-platform debug information level.
If this file comes from a NuGet package, update to a newer version of the NuGet package or notify the library author.	Phoneword.Android			
```

**Comment by oscarrojasacc** [comment]
It's because of the length of the path where you cloned the repo, move the folder to a shorter path like "C:\\...", also happened to me 😅😅

> Note
>
>If you are planning to run and debug your Xamarin apps on Android from Windows, it is best to clone or download the >exercise content to a short folder path, such as C:\dev\, to avoid build-generated files exceeding the maximum path length.

That note appears [here](https://docs.microsoft.com/en-us/learn/modules/create-ui-in-xamarin-forms-apps-with-xaml/5-exercise-create-your-first-xaml-page) in the learning docs

Check this stackoverflow [answer](https://stackoverflow.com/questions/54361545/xamarin-android-build-error-failed-to-create-javatypeinfo-for-class)

**Comment by DeveloQueer** [comment]
oh rip XD

I had the problem but with different warning messages, that's why this time it concerned me.
Well, I hope it's ok to feel embarassed.

Thanks!
